### ISSUE TITLE
🐛 [Bug Report] Unable to compile all cores

### ISSUE THREAD

**Issue by f0n1x** [cmangos/issues#3667]
### Bug Details

Compilation is failing on all cmangos cores. This might be a duplicate of #3666 and happy to close if it is, but that issue might be unique to wotlk? I'll need someone smarter than me to confirm.

As a side-note, I compile with clang since gcc 11.2 has issues, and I've been doing so since I found the project almost 2 years ago.

### Steps to Reproduce

1. Pull current
2. Compile

### Expected behavior

Compile completion

### Crash Log

In file included from <built-in>:1:
In file included from /tmp/SBo/mangos-classic-508a96d744b071fcffcace790b48fc22fb438c0e/build/src/game/CMakeFiles/game.dir/cmake_pch.hxx:5:
In file included from /tmp/SBo/mangos-classic-508a96d744b071fcffcace790b48fc22fb438c0e/src/game/pchdef.h:11:
In file included from /usr/bin/../lib64/gcc/x86_64-slackware-linux/11.2.0/../../../../include/c++/11.2.0/cmath:1927:
In file included from /usr/bin/../lib64/gcc/x86_64-slackware-linux/11.2.0/../../../../include/c++/11.2.0/bits/specfun.h:45:
In file included from /usr/bin/../lib64/gcc/x86_64-slackware-linux/11.2.0/../../../../include/c++/11.2.0/bits/stl_algobase.h:64:
/usr/bin/../lib64/gcc/x86_64-slackware-linux/11.2.0/../../../../include/c++/11.2.0/bits/stl_pair.h:218:11: error: field has incomplete type 'LootTemplate'
      _T2 second;                ///< The second member
          ^
/usr/bin/../lib64/gcc/x86_64-slackware-linux/11.2.0/../../../../include/c++/11.2.0/ext/aligned_buffer.h:91:28: note: in instantiation of template class 'std::pair<const unsigned int, LootTemplate>' requested here
    : std::aligned_storage<sizeof(_Tp), __alignof__(_Tp)>
                           ^
/usr/bin/../lib64/gcc/x86_64-slackware-linux/11.2.0/../../../../include/c++/11.2.0/bits/hashtable_policy.h:233:43: note: in instantiation of template class '__gnu_cxx::__aligned_buffer<std::pair<const unsigned int, LootTemplate>>' requested here
      __gnu_cxx::__aligned_buffer<_Value> _M_storage;
                                          ^
/usr/bin/../lib64/gcc/x86_64-slackware-linux/11.2.0/../../../../include/c++/11.2.0/bits/hashtable_policy.h:268:7: note: in instantiation of template class 'std::__detail::_Hash_node_value_base<std::pair<const unsigned int, LootTemplate>>' requested here
    : _Hash_node_value_base<_Value>
      ^
/usr/bin/../lib64/gcc/x86_64-slackware-linux/11.2.0/../../../../include/c++/11.2.0/bits/hashtable_policy.h:278:7: note: in instantiation of template class 'std::__detail::_Hash_node_value<std::pair<const unsigned int, LootTemplate>, false>' requested here
    , _Hash_node_value<_Value, _Cache_hash_code>
      ^
/usr/bin/../lib64/gcc/x86_64-slackware-linux/11.2.0/../../../../include/c++/11.2.0/bits/hashtable_policy.h:1810:25: note: in instantiation of template class 'std::__detail::_Hash_node<std::pair<const unsigned int, LootTemplate>, false>' requested here
        rebind_traits<typename __node_type::value_type>;
                               ^
/usr/bin/../lib64/gcc/x86_64-slackware-linux/11.2.0/../../../../include/c++/11.2.0/bits/hashtable_policy.h:810:42: note: in instantiation of template class 'std::__detail::_Hashtable_alloc<std::allocator<std::__detail::_Hash_node<std::pair<const unsigned int, LootTemplate>, false>>>' requested here
      using __node_alloc_type = typename __hashtable_alloc::__node_alloc_type;
                                         ^
/usr/bin/../lib64/gcc/x86_64-slackware-linux/11.2.0/../../../../include/c++/11.2.0/bits/hashtable_policy.h:1005:14: note: in instantiation of template class 'std::__detail::_Insert_base<unsigned int, std::pair<const unsigned int, LootTemplate>, std::allocator<std::pair<const unsigned int, LootTemplate>>, std::__detail::_Select1st, std::equal_to<unsigned int>, std::hash<unsigned int>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true>>' requested here
    : public _Insert_base<_Key, _Value, _Alloc, _ExtractKey, _Equal,
             ^
/usr/bin/../lib64/gcc/x86_64-slackware-linux/11.2.0/../../../../include/c++/11.2.0/bits/hashtable.h:174:14: note: in instantiation of template class 'std::__detail::_Insert<unsigned int, std::pair<const unsigned int, LootTemplate>, std::allocator<std::pair<const unsigned int, LootTemplate>>, std::__detail::_Select1st, std::equal_to<unsigned int>, std::hash<unsigned int>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true>, false>' requested here
      public __detail::_Insert<_Key, _Value, _Alloc, _ExtractKey, _Equal,
             ^
/usr/bin/../lib64/gcc/x86_64-slackware-linux/11.2.0/../../../../include/c++/11.2.0/bits/unordered_map.h:105:18: note: in instantiation of template class 'std::_Hashtable<unsigned int, std::pair<const unsigned int, LootTemplate>, std::allocator<std::pair<const unsigned int, LootTemplate>>, std::__detail::_Select1st, std::equal_to<unsigned int>, std::hash<unsigned int>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true>>' requested here
      _Hashtable _M_h;
                 ^
/tmp/SBo/mangos-classic-508a96d744b071fcffcace790b48fc22fb438c0e/src/game/Loot/LootMgr.h:293:25: note: in instantiation of template class 'std::unordered_map<unsigned int, LootTemplate>' requested here
        LootTemplateMap m_LootTemplates;
                        ^
/tmp/SBo/mangos-classic-508a96d744b071fcffcace790b48fc22fb438c0e/src/game/Loot/LootMgr.h:35:7: note: forward declaration of 'LootTemplate'
class LootTemplate;
      ^
In file included from <built-in>:1:
In file included from /tmp/SBo/mangos-classic-508a96d744b071fcffcace790b48fc22fb438c0e/build/src/game/CMakeFiles/game.dir/cmake_pch.hxx:5:
In file included from /tmp/SBo/mangos-classic-508a96d744b071fcffcace790b48fc22fb438c0e/src/game/pchdef.h:21:
In file included from /usr/bin/../lib64/gcc/x86_64-slackware-linux/11.2.0/../../../../include/c++/11.2.0/algorithm:74:
In file included from /usr/bin/../lib64/gcc/x86_64-slackware-linux/11.2.0/../../../../include/c++/11.2.0/pstl/glue_algorithm_defs.h:13:
In file included from /usr/bin/../lib64/gcc/x86_64-slackware-linux/11.2.0/../../../../include/c++/11.2.0/functional:61:
In file included from /usr/bin/../lib64/gcc/x86_64-slackware-linux/11.2.0/../../../../include/c++/11.2.0/unordered_map:46:
In file included from /usr/bin/../lib64/gcc/x86_64-slackware-linux/11.2.0/../../../../include/c++/11.2.0/bits/hashtable.h:35:
/usr/bin/../lib64/gcc/x86_64-slackware-linux/11.2.0/../../../../include/c++/11.2.0/bits/hashtable_policy.h:1011:48: error: 'value_type' is a protected member of 'std::__detail::_Insert_base<unsigned int, std::pair<const unsigned int, LootTemplate>, std::allocator<std::pair<const unsigned int, LootTemplate>>, std::__detail::_Select1st, std::equal_to<unsigned int>, std::hash<unsigned int>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true>>'
      using value_type = typename __base_type::value_type;
                                               ^
/usr/bin/../lib64/gcc/x86_64-slackware-linux/11.2.0/../../../../include/c++/11.2.0/bits/hashtable.h:174:14: note: in instantiation of template class 'std::__detail::_Insert<unsigned int, std::pair<const unsigned int, LootTemplate>, std::allocator<std::pair<const unsigned int, LootTemplate>>, std::__detail::_Select1st, std::equal_to<unsigned int>, std::hash<unsigned int>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true>, false>' requested here
      public __detail::_Insert<_Key, _Value, _Alloc, _ExtractKey, _Equal,
             ^
/usr/bin/../lib64/gcc/x86_64-slackware-linux/11.2.0/../../../../include/c++/11.2.0/bits/unordered_map.h:105:18: note: in instantiation of template class 'std::_Hashtable<unsigned int, std::pair<const unsigned int, LootTemplate>, std::allocator<std::pair<const unsigned int, LootTemplate>>, std::__detail::_Select1st, std::equal_to<unsigned int>, std::hash<unsigned int>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true>>' requested here
      _Hashtable _M_h;
                 ^
/tmp/SBo/mangos-classic-508a96d744b071fcffcace790b48fc22fb438c0e/src/game/Loot/LootMgr.h:293:25: note: in instantiation of template class 'std::unordered_map<unsigned int, LootTemplate>' requested here
        LootTemplateMap m_LootTemplates;
                        ^
/usr/bin/../lib64/gcc/x86_64-slackware-linux/11.2.0/../../../../include/c++/11.2.0/bits/hashtable_policy.h:806:13: note: declared protected here
      using value_type = typename __hashtable_base::value_type;
            ^
/usr/bin/../lib64/gcc/x86_64-slackware-linux/11.2.0/../../../../include/c++/11.2.0/bits/hashtable_policy.h:1015:51: error: '__unique_keys' is a protected member of 'std::__detail::_Insert_base<unsigned int, std::pair<const unsigned int, LootTemplate>, std::allocator<std::pair<const unsigned int, LootTemplate>>, std::__detail::_Select1st, std::equal_to<unsigned int>, std::hash<unsigned int>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true>>'
      using __unique_keys = typename __base_type::__unique_keys;
                                                  ^
/usr/bin/../lib64/gcc/x86_64-slackware-linux/11.2.0/../../../../include/c++/11.2.0/bits/hashtable_policy.h:809:13: note: declared protected here
      using __unique_keys = typename _Traits::__unique_keys;
            ^
/usr/bin/../lib64/gcc/x86_64-slackware-linux/11.2.0/../../../../include/c++/11.2.0/bits/hashtable_policy.h:1016:49: error: '__hashtable' is a protected member of 'std::__detail::_Insert_base<unsigned int, std::pair<const unsigned int, LootTemplate>, std::allocator<std::pair<const unsigned int, LootTemplate>>, std::__detail::_Select1st, std::equal_to<unsigned int>, std::hash<unsigned int>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true>>'
      using __hashtable = typename __base_type::__hashtable;
                                                ^
/usr/bin/../lib64/gcc/x86_64-slackware-linux/11.2.0/../../../../include/c++/11.2.0/bits/hashtable_policy.h:795:13: note: declared protected here
      using __hashtable = _Hashtable<_Key, _Value, _Alloc, _ExtractKey, _Equal,
            ^
In file included from <built-in>:1:
In file included from /tmp/SBo/mangos-classic-508a96d744b071fcffcace790b48fc22fb438c0e/build/src/game/CMakeFiles/game.dir/cmake_pch.hxx:5:
In file included from /tmp/SBo/mangos-classic-508a96d744b071fcffcace790b48fc22fb438c0e/src/game/pchdef.h:21:
In file included from /usr/bin/../lib64/gcc/x86_64-slackware-linux/11.2.0/../../../../include/c++/11.2.0/algorithm:74:
In file included from /usr/bin/../lib64/gcc/x86_64-slackware-linux/11.2.0/../../../../include/c++/11.2.0/pstl/glue_algorithm_defs.h:13:
In file included from /usr/bin/../lib64/gcc/x86_64-slackware-linux/11.2.0/../../../../include/c++/11.2.0/functional:61:
In file included from /usr/bin/../lib64/gcc/x86_64-slackware-linux/11.2.0/../../../../include/c++/11.2.0/unordered_map:46:
/usr/bin/../lib64/gcc/x86_64-slackware-linux/11.2.0/../../../../include/c++/11.2.0/bits/hashtable.h:227:24: error: type 'std::_Hashtable<unsigned int, std::pair<const unsigned int, LootTemplate>, std::allocator<std::pair<const unsigned int, LootTemplate>>, std::__detail::_Select1st, std::equal_to<unsigned int>, std::hash<unsigned int>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true>>::__value_alloc_traits' (aka 'int') cannot be used prior to '::' because it has no members
      typedef typename __value_alloc_traits::pointer            pointer;
                       ^
/usr/bin/../lib64/gcc/x86_64-slackware-linux/11.2.0/../../../../include/c++/11.2.0/bits/unordered_map.h:105:18: note: in instantiation of template class 'std::_Hashtable<unsigned int, std::pair<const unsigned int, LootTemplate>, std::allocator<std::pair<const unsigned int, LootTemplate>>, std::__detail::_Select1st, std::equal_to<unsigned int>, std::hash<unsigned int>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true>>' requested here
      _Hashtable _M_h;
                 ^
/tmp/SBo/mangos-classic-508a96d744b071fcffcace790b48fc22fb438c0e/src/game/Loot/LootMgr.h:293:25: note: in instantiation of template class 'std::unordered_map<unsigned int, LootTemplate>' requested here
        LootTemplateMap m_LootTemplates;
                        ^
In file included from <built-in>:1:
In file included from /tmp/SBo/mangos-classic-508a96d744b071fcffcace790b48fc22fb438c0e/build/src/game/CMakeFiles/game.dir/cmake_pch.hxx:5:
In file included from /tmp/SBo/mangos-classic-508a96d744b071fcffcace790b48fc22fb438c0e/src/game/pchdef.h:21:
In file included from /usr/bin/../lib64/gcc/x86_64-slackware-linux/11.2.0/../../../../include/c++/11.2.0/algorithm:74:
In file included from /usr/bin/../lib64/gcc/x86_64-slackware-linux/11.2.0/../../../../include/c++/11.2.0/pstl/glue_algorithm_defs.h:13:
In file included from /usr/bin/../lib64/gcc/x86_64-slackware-linux/11.2.0/../../../../include/c++/11.2.0/functional:61:
In file included from /usr/bin/../lib64/gcc/x86_64-slackware-linux/11.2.0/../../../../include/c++/11.2.0/unordered_map:46:
/usr/bin/../lib64/gcc/x86_64-slackware-linux/11.2.0/../../../../include/c++/11.2.0/bits/hashtable.h:228:24: error: type 'std::_Hashtable<unsigned int, std::pair<const unsigned int, LootTemplate>, std::allocator<std::pair<const unsigned int, LootTemplate>>, std::__detail::_Select1st, std::equal_to<unsigned int>, std::hash<unsigned int>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true>>::__value_alloc_traits' (aka 'int') cannot be used prior to '::' because it has no members
      typedef typename __value_alloc_traits::const_pointer      const_pointer;
                       ^
In file included from <built-in>:1:
In file included from /tmp/SBo/mangos-classic-508a96d744b071fcffcace790b48fc22fb438c0e/build/src/game/CMakeFiles/game.dir/cmake_pch.hxx:5:
In file included from /tmp/SBo/mangos-classic-508a96d744b071fcffcace790b48fc22fb438c0e/src/game/pchdef.h:21:
In file included from /usr/bin/../lib64/gcc/x86_64-slackware-linux/11.2.0/../../../../include/c++/11.2.0/algorithm:74:
In file included from /usr/bin/../lib64/gcc/x86_64-slackware-linux/11.2.0/../../../../include/c++/11.2.0/pstl/glue_algorithm_defs.h:13:
In file included from /usr/bin/../lib64/gcc/x86_64-slackware-linux/11.2.0/../../../../include/c++/11.2.0/functional:61:
In file included from /usr/bin/../lib64/gcc/x86_64-slackware-linux/11.2.0/../../../../include/c++/11.2.0/unordered_map:47:
/usr/bin/../lib64/gcc/x86_64-slackware-linux/11.2.0/../../../../include/c++/11.2.0/bits/unordered_map.h:113:36: error: no type named 'mapped_type' in 'std::_Hashtable<unsigned int, std::pair<const unsigned int, LootTemplate>, std::allocator<std::pair<const unsigned int, LootTemplate>>, std::__detail::_Select1st, std::equal_to<unsigned int>, std::hash<unsigned int>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true>>'
      typedef typename _Hashtable::mapped_type  mapped_type;
              ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~
/tmp/SBo/mangos-classic-508a96d744b071fcffcace790b48fc22fb438c0e/src/game/Loot/LootMgr.h:293:25: note: in instantiation of template class 'std::unordered_map<unsigned int, LootTemplate>' requested here
        LootTemplateMap m_LootTemplates;
                        ^
In file included from <built-in>:1:
In file included from /tmp/SBo/mangos-classic-508a96d744b071fcffcace790b48fc22fb438c0e/build/src/game/CMakeFiles/game.dir/cmake_pch.hxx:5:
In file included from /tmp/SBo/mangos-classic-508a96d744b071fcffcace790b48fc22fb438c0e/src/game/pchdef.h:21:
In file included from /usr/bin/../lib64/gcc/x86_64-slackware-linux/11.2.0/../../../../include/c++/11.2.0/algorithm:74:
In file included from /usr/bin/../lib64/gcc/x86_64-slackware-linux/11.2.0/../../../../include/c++/11.2.0/pstl/glue_algorithm_defs.h:13:
In file included from /usr/bin/../lib64/gcc/x86_64-slackware-linux/11.2.0/../../../../include/c++/11.2.0/functional:61:
In file included from /usr/bin/../lib64/gcc/x86_64-slackware-linux/11.2.0/../../../../include/c++/11.2.0/unordered_map:47:
/usr/bin/../lib64/gcc/x86_64-slackware-linux/11.2.0/../../../../include/c++/11.2.0/bits/unordered_map.h:114:36: error: no type named 'hasher' in 'std::_Hashtable<unsigned int, std::pair<const unsigned int, LootTemplate>, std::allocator<std::pair<const unsigned int, LootTemplate>>, std::__detail::_Select1st, std::equal_to<unsigned int>, std::hash<unsigned int>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true>>'
      typedef typename _Hashtable::hasher       hasher;
              ~~~~~~~~~~~~~~~~~~~~~^~~~~~
8 errors generated.

### Core SHA1 Commit Hash

508a96d744b071fcffcace790b48fc22fb438c0e

### Database SHA1 Commit Hash

1d156da99ade32311ff944062893991beae6e7e1

### Operating System

Slackware64-15.0

### Client Version

1.12.1 (Classic)

**Comment by insunaa** [comment]
Duplicate of https://github.com/cmangos/issues/issues/3666
Appreciate the PRs tho.
