### ISSUE TITLE
🐛 [Bug Report] (Classic) Unable to build on Ubuntu 16.04 LTS: boost/stacktrace.hpp not found

### ISSUE THREAD

**Issue by nate123456** [cmangos/issues#2456]
## 🐛 Bugreport
When attempting to build classic mangos, the following error is thrown after running the `make` command:

`src/shared/Log.cpp:32:32: fatal error: boost/stacktrace.hpp: No such file or directory`

I verified that I had boost installed. I also verified that the file referenced by the error is not anywhere on disk- it seems that boost on Linux does not have this file.

### Expected behavior
Build to succeed when building off master.

### Version & Environment
Client Version: n/a

CMaNGOS Repo & Commit Hash: 
[This](https://github.com/cmangos/mangos-classic/commit/0a7b15dfac537dfaf24c4879d3238fa4530f88b3#diff-93eef7c860a081602c2a653fabf9e763c4384496c22aeb72cb110c0ff2d03991) link points to the commit where the line of code was added that throws the error.

Database Repo & Commit Hash: 
n/a

Operating System: Ubuntu 16.04

### Steps to reproduce
1. Pull latest mangos-classic code to Linux Ubuntu 16.04 machine
2. Attempt to build as per installation instructions
3. `make` command fails with above error message

**Comment by nate123456** [comment]
I was able to avoid the issue by upgrading to Ubuntu 18.04.5 LTS and installing the required packages as per the installation documentation. It appears that the `libboost` package for this version of Ubuntu contains the file referenced in the new changes as per the commit linked in the original post.

Perhaps this issue could be grounds for updating the [compatibility](https://github.com/cmangos/issues/wiki/CMake-to-Boost-Version-Compatibility-Table) table to reflect that it will not build on 16.04.

**Comment by killerwife** [comment]
It will indeed compile on Ubuntu 16.04 however you have to manually upgrade your libboost package to above what 16.04 has in its apt-get repository by default. I think it changed in boost around 1.57 or similar. Since cmangos is actively maintained, we cannot at this point 5 year old distros :| I will close this issue and hopefully it will give everyone who reads this in the future needed info how to approach this.

**Comment by evil-at-wow** [comment]
FYI: the Stacktrace library was added in boost 1.65. So you need at least that boost version out of the box.

**Comment by Nate129** [comment]
Good to know. I might have missed it, but the boost library versions available for 16.04 only listed one version installable via `apt-get` (1.58 I think). That's the reason I made the issue. If 16.04 is required in someone's setup, the fix would be to manually install/build boost from source as @killerwife suggested. It seems to me that building from source is more trouble than it's worth; upgrading to 18.04 seems to have no downsides other than a little time, at least for my case. 

Thanks for the help!
