### ISSUE TITLE
🐛 [Bug Report] Compiling CMaNGOS. fatal error: filesystem: No such file or directory

### ISSUE THREAD

**Issue by maxsl89** [cmangos/issues#2635]
### Bug Details

Ubuntu 18.04
mysql 5.7

error while compile on 94%

### Steps to Reproduce

1. Wrath of the Lich King:
2. cmake ../mangos -DCMAKE_INSTALL_PREFIX=\../mangos/run -DBUILD_EXTRACTORS=ON -DPCH=1 -DDEBUG=1
3. make j2
4. wait until 94%

### Expected behavior

successfull compile

### Crash Log

[ 94%] Building CXX object src/game/CMakeFiles/game.dir/Reputation/ReputationMgr.cpp.o
[ 94%] Building CXX object src/game/CMakeFiles/game.dir/Server/DBCStores.cpp.o
/home/mangos/mangos/src/game/Server/DBCStores.cpp:31:10: fatal error: filesystem: No such file or directory
 **#include <filesystem>
          ^~~~~~~~~~~~**
compilation terminated.
src/game/CMakeFiles/game.dir/build.make:10860: recipe for target 'src/game/CMakeFiles/game.dir/Server/DBCStores.cpp.o' failed
make[2]: *** [src/game/CMakeFiles/game.dir/Server/DBCStores.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:640: recipe for target 'src/game/CMakeFiles/game.dir/all' failed
make[1]: *** [src/game/CMakeFiles/game.dir/all] Error 2
Makefile:135: recipe for target 'all' failed
make: *** [all] Error 2

### Core SHA1 Commit Hash

5fefe5c0a15115f57258cd9dda8d250bfc0780b5

### Database SHA1 Commit Hash

99b0f4b96aa84854c50433a8b6aba01c3ca5e486

### Operating System

ubuntu 18.04

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by insunaa** [comment]
You require a compiler capable of C++17, at least gcc 8 or clang 5.
If you do have them, but had the project previously compiled already, you need to rerun cmake

**Comment by maxsl89** [comment]
Thank you @insunaa, it helps.
I have installed gcc 8.
progress reached 100%
but in the end i got this:

[100%] Building CXX object src/mangosd/CMakeFiles/mangosd.dir/soapServer.cpp.o
[100%] Linking CXX executable mangosd
../game/libgame.a(DBCStores.cpp.o): In function `LoadDBCStores(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
DBCStores.cpp:(.text+0x223b): undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'
DBCStores.cpp:(.text+0x2243): undefined reference to `std::filesystem::status(std::filesystem::__cxx11::path const&)'
collect2: error: ld returned 1 exit status
src/mangosd/CMakeFiles/mangosd.dir/build.make:228: recipe for target 'src/mangosd/mangosd' failed
make[2]: *** [src/mangosd/mangosd] Error 1
CMakeFiles/Makefile2:671: recipe for target 'src/mangosd/CMakeFiles/mangosd.dir/all' failed
make[1]: *** [src/mangosd/CMakeFiles/mangosd.dir/all] Error 2
Makefile:135: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by insunaa** [comment]
The linker is still confused. Did you rerun cmake?

**Comment by maxsl89** [comment]
yep, i have delete build folder and  rerun this cmake ../mangos -DCMAKE_INSTALL_PREFIX=../mangos/run -DBUILD_EXTRACTORS=ON -DPCH=1 -DDEBUG=0 before make

**Comment by insunaa** [comment]
OK, then this feature might require gcc9 to work without modification.
For the time being do this: open the CMakeList.txt in the mangos-wotlk directory and in some free line that's not surrounded by an if() block put this:

```cmake
link_libraries(stdc++fs)
```

**Comment by killerwife** [comment]
GCC 9 is indeed required. It is possible to install GCC 9 on 18.04 with a bit of fiddling however.

**Comment by maxsl89** [comment]
installed gcc9, helped!
Thank you guys!

**Comment by Warlockbugs** [comment]
The minimum supported compilers are now clarified as GCC 8.0 and CLang 7.0.

**Comment by Warlockbugs** [comment]
The GCC requirement was reduced to GCC 7.0, so now it should work on a fully updated 18.04.
