### ISSUE TITLE
[Classic] Server Crash - Object.h GetMap failed

### ISSUE THREAD

**Issue by Trystanosaurus** [cmangos/issues#1535]
**Current behavior**: 
There seems to be a random crash, possibly introduced in dc3acae (at least for me). The last messages I got in the server log were..

WORLD: Received opcode CMSG_ZONEUPDATE: newzone is 10
c:\emulators\mmos\world of warcraft\backups and other stuff\compiling mangos\mangos-classic-master\src\game\Entities/Object.h:825: Error: Assertion in WorldObject::GetMap failed: m_currMap

I was just running around Darkshire. The first time I got the crash after about 5 mins of playing, the second time it crashed after around an hour. I'm recompiling the server in debug now so if it happens again I'll update this issue.

**Expected behavior**: 
The server doesn't crash.

**Steps to reproduce**:

1. I'm not that sure, both of my crashes happened in Darkshire but that might have been (bad) luck. I was just running around both times, so there's not specific trigger I could see.
2. 
3. 

**Client version**: 1.12.1

**Commit hash**: dc3acae

**Database version**: Below Blackrock Mountain 1.8.5 -  336b905

**Operating system**: Windows 10

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by Trystanosaurus** [comment]
I've just left the server going again (debug build), it crashed after an hour or so with the same error. This time I'd played for around 5 minutes but was logged out when the crash occurred. 

The last messages in the server log are below. I don't have a crash log that I can see, though I may just be missing it. If there is anything else you need, please let me know.

Sending SMSG_SPELL_GO id=12625
Map::GetHitPosition vmaps corrects gained with static objects! new dest coords are X:-7562.550781 Y:1525.303101 Z:3.375970
Map::GetHitPosition vmaps corrects gained with static objects! new dest coords are X:6833.569336 Y:-1871.488770 Z:551.551025
Sending SMSG_SPELL_GO id=12625
Remove object (GUID: 10 TypeId:3) from grid[38,25]
c:\emulators\mmos\world of warcraft\backups and other stuff\compiling mangos\mangos-classic-master\src\game\Entities/Object.h:825: Error: Assertion in WorldObject::GetMap failed: m_currMap

**Comment by Warlockbugs** [comment]
This should do it:
https://github.com/cmangos/mangos-classic/commit/9ce621b3392da2d9a78e25d1fb2c0e7fcab5aef0
https://github.com/cmangos/mangos-tbc/commit/e894ba22ea71f2ccecf8fa9e1818c9b4a94434ec
https://github.com/cmangos/mangos-wotlk/commit/25ca64b108090d4d7f26fa99c0158185b8a8a8d7
