### ISSUE TITLE
Compilation errors with OpenSSL-1.1.0 (EVP_CIPHER_CTX & HMAC_CTX)

### ISSUE THREAD

**Issue by elipp** [cmangos/issues#1381]
**Current behavior**: 
Doesn't compile on linux with OpenSSL-1.1.0. Getting compilation errors relating to the fact that all structs have apparently been made "opaque" in this version of the library, namely EVP_CIPHER_CTX and HMAC_CTX (see: https://wiki.openssl.org/index.php/OpenSSL_1.1.0_Changes)

**Expected behavior**: 
Should compile.

**Steps to reproduce**:

1. cmake && make.
2. 
3. 

**Client version**: 
3.3.5a
**Commit hash**: 
fd82cb43b55b90f5194f7a1223327bea39fc7505
**Database version**: 
mariadb 10.1.24
**Operating system**: 
Arch Linux (64-bit)

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by Warlockbugs** [comment]
AFAIK we specifically state that 1.1.0 branch is not supported at the moment. According to the OpenSSL website, 1.0.2 branch will be supported until 2019-12-31 (LTS), longer than current release of 1.1.0 branch (2018-08-31). Is there any specific problem that may warrant a rewrite and switch to 1.1.0 sooner?

**Comment by elipp** [comment]
Oh, I see - nvm then I guess :)

Having just upgraded my Arch server to the latest packages (including openssl-1.1.0 and a ton of dependencies), this just puts me personally in a bit of an awkward position, since downgrading isn't really a feasible option. No can do I guess.

Could there, idk, be at least some kind of warning in the main cmake file to let the user know that it isn't supported?

**Comment by Lillecarl** [comment]
You can download and compile openssl yourself with another location and link towards that version instead :) So your system can run 1.1 while cmangos runs 1.0 :)

**Comment by elipp** [comment]
Tried that too: the result was linker errors with regards to libmysqlclient also having been built against a different version of openssl, and probably the same would apply to a lot of packages after that... I went ahead and made a rollback to a previous snapshot of the whole Arch Package database (using Arch Linux Archive), so the problem is probably fixed. Waiting to compile.

**Comment by Lillecarl** [comment]
If you have a server dedicated to CMaNGOS i'd recommend sticking to Ubuntu, considering we're using Ubuntu 14.04 for CI (Travis CI) that's the system most likely to work.

**Comment by Warlockbugs** [comment]
Backward compatibility with distros which still provide OpenSSL-1.0 package should be improved after https://github.com/cmangos/mangos-wotlk/commit/eddeff7fe9ba49ee1dc2ae7df31c0b1fca4bf247.
Dont forget to install OpenSSL-1.0 package. :smile:
